ROOM_NAME_BY_ID = {
    "((store))": "Wizzes' storeroom",
    "((wwork))": "wizzes' workshop",
    "Limbo": "limbo",
    "abcell": "abbot's cell",
    "acavn1": "above cavern",
    "acavn2": "above cavern",
    "acavn3": "above cavern",
    "alcove": "alcove",
    "balcon": "balcony",
    "balnea": "balneary",
    "bar": "public bar",
    "bbar": "behind bar",
    "bdrm1": "bedroom",
    "bdrm2": "bedroom",
    "bdrm3": "small bedroom",
    "beerst": "beer store",
    "bfood": "bar food store",
    "bitbox": "bit box",
    "bkitch": "bar kitchen",
    "cbarn": "barn",
    "cbed1": 'bedroom in "il castellare"',
    "cbed2": 'bedroom in "il castellare"',
    "cbthrm": 'bathroom in "il castellare"',
    "ccorr1": 'corridor in "il castellare"',
    "ccorr2": 'corridor in "il castellare"',
    "ccorr3": 'corridor in "il castellare"',
    "cdayrm": 'dayroom in "il castellare"',
    "cdinrm": 'dining room in "il castellare"',
    "cenbrm": "en suite bathroom",
    "cflowrm": "flower room",
    "cforect": "forecourt",
    "cgames": "games room",
    "ckitch": 'kitchen in "il castellare"',
    "clogdn": "garden in cloister",
    "cmusrm": "music room",
    "coalrm": "coal room",
    "cobbl1": "cobbled yard",
    "cobbl2": "cobbled yard",
    "cobbl3": "cobbled yard",
    "confrm": "conference room",
    "costar": "cave of stars",
    "cpath1": "narrow pathway",
    "cpath2": "narrow pathway",
    "cporch": 'back entrance to "il castellare"',
    "cruin": "classical ruin",
    "cshowrm": "shower room",
    "csroom": 'sitting room in "il castellare"',
    "cstore": "cold storage",
    "cterrac": "terrace",
    "ctyard": "courtyard",
    "dormit": "dormitory",
    "dryps1": "dry passage",
    "dryps2": "dry passage",
    "dway1": "driveway",
    "dway2": "driveway",
    "dway3": "driveway",
    "ealc": "east alcove",
    "eante": "east antechamber",
    "eatrm": "eating room",
    "eattic": "east part of attic",
    "edge1": "edge of underground stream",
    "edge2": "edge of underground stream",
    "enlps1": "enlarged passage",
    "enlps2": "enlarged passage",
    "enlps3": "enlarged passage",
    "enlps4": "enlarged passage",
    "etearm": "Elizabethan tearoom",
    "fishrm": "fishing room",
    "garbour": "arbour",
    "gaviary": "aviary",
    "gbeech": "avenue of beeches",
    "gbefchi": "exterior of chinese house",
    "gchesnt": "avenue of chestnuts",
    "gchinhse": "chinese house",
    "gclear": "clearing in luscious wood",
    "gcoop": "chicken coop",
    "gcow": "cowshed",
    "gcroquet": "croquet lawn",
    "gdove": "dovecote",
    "gdyerm": "dyeroom",
    "gedeer": "deerpark",
    "gfen": "fen",
    "gfield1": "field",
    "gfield2": "field",
    "gflower": "flower garden",
    "gfolly": "folly",
    "gfount": "fountain in formal garden",
    "gfox": "foxhill",
    "ggbank1": "bank of river",
    "ggbank2": "bank of river",
    "ggbean": "beanfield",
    "ggbefc": "before cave",
    "ggbefs": "before shrine",
    "ggbotr": "bottom of trench",
    "ggbull": "bull pen",
    "ggcabb": "cabbage patch",
    "ggcave": "black cave",
    "ggccav1": "north part of circular cavern",
    "ggccav2": "east part of circular cavern",
    "ggccav3": "south part of circular cavern",
    "ggccav4": "west part of circular cavern",
    "ggcfire": "cooking area",
    "ggcows": "cowfield",
    "ggdbd": "giant bedroom",
    "ggdux": "duckpond",
    "gged1": "inside goblin dwelling",
    "gged2": "north part of goblin dwelling",
    "gged3": "east part of goblin dwelling",
    "gged4": "south part of goblin dwelling",
    "ggefiss": "east fissure",
    "ggfall": "fallow field",
    "ggfell": "felled trees",
    "ggfire": "great fire",
    "ggfrst": "dense forest",
    "gggrass1": "deep grass",
    "gggrass2": "deep grass",
    "gggrass3": "deep grass",
    "gggrass4": "deep grass",
    "gggswd": "grassy sward",
    "ggguard": "guard room",
    "gghost1": "ghostwalk",
    "gghost2": "ghostwalk",
    "ggibdr": "behind giant back door",
    "ggifdr": "behind giant front door",
    "ggkitch": "giant kitchen",
    "gglard": "giant larder",
    "gglett": "lettuce patch",
    "ggmidd": "midden",
    "ggnd1": "inside goblin dwelling",
    "ggnd2": "north part of goblin dwelling",
    "ggnd3": "east part of goblin dwelling",
    "ggnd4": "south part of goblin dwelling",
    "ggnf1": "narrow fissure",
    "ggnf2": "narrow fissure",
    "ggnf3": "narrow fissure",
    "ggnf4": "narrow fissure",
    "ggogob": "outside goblin dwellings",
    "ggonbed0": "on giant double bed",
    "ggonbed1": "on giant bed",
    "ggonbed2": "on giant bed",
    "ggonch0": "on giant chair",
    "ggonch1": "on giant chair",
    "ggonsofa": "on giant sofa",
    "ggontb": "on giant table",
    "ggreen": "greenhouse",
    "ggrp1": "rutted path",
    "ggrp2": "rutted path",
    "ggsbd0": "giant bedroom",
    "ggsbd1": "giant bedroom",
    "ggsd1": "inside goblin dwelling",
    "ggsd2": "north part of goblin dwelling",
    "ggsd3": "east part of goblin dwelling",
    "ggsd4": "south part of goblin dwelling",
    "ggsgdn": "scrappy gardens",
    "ggshed": "inside giant shed",
    "ggsitt": "giant sitting room",
    "ggsoot": "sooty tunnel",
    "ggstack": "haystack",
    "ggston1": "stony ground",
    "ggston2": "stony ground",
    "ggstrng": "giant strongroom",
    "ggubed0": "under giant double bed",
    "ggubed1": "under giant bed",
    "ggubed2": "under giant bed",
    "gguch0": "under giant chair",
    "gguch1": "under giant chair",
    "ggutb": "under giant table",
    "ggvwp": "very wide path",
    "ggwf1": "wide fissure",
    "ggwf2": "wide fissure",
    "ggwf3": "wide fissure",
    "ggwf4": "wide fissure",
    "ggwf5": "wide fissure",
    "ggwf6": "wide fissure",
    "ggwfiss": "west fissure",
    "ggwheat": "wheatfield",
    "ggwste": "waste ground",
    "ggyard": "yard",
    "ghaha1": "western end of haha",
    "ghaha2": "haha centre",
    "ghaha3": "eastern end of haha",
    "gherb": "herb garden in formal garden",
    "ghide": "hide by dark pond",
    "ghornb": "hornbeam alley",
    "gkeep1": "keep",
    "gkeep2": "ground floor of keep",
    "gkeep3": "first floor of keep",
    "gkeep4": "second floor of keep",
    "gkeep5": "third floor of keep",
    "gkeep6": "fourth floor of keep",
    "gkeep7": "top floor of keep",
    "gknot": "knot garden",
    "gktreas": "treasure chamber in keep",
    "glake": "man-made lake",
    "glakedge": "lakedge",
    "glawn": "lawn",
    "glimes": "avenue of limes",
    "gloom": "loom room",
    "gmaz1": "you are wandering in a pleasant maze of hedges.",
    "gmaz10": "maze of hedges",
    "gmaz11": "maze of hedges",
    "gmaz12": "maze of hedges",
    "gmaz13": "maze of hedges",
    "gmaz14": "maze of hedges",
    "gmaz15": "maze of hedges",
    "gmaz16": "maze of hedges",
    "gmaz17": "you are wandering in a pleasant maze of hedges.",
    "gmaz18": "you are wandering in a pleasant maze of hedges.",
    "gmaz19": "maze of hedges",
    "gmaz2": "maze of hedges",
    "gmaz20": "you are wandering in a pleasant maze of hedges.",
    "gmaz21": "maze of hedges",
    "gmaz22": "maze of hedges",
    "gmaz23": "you are wandering in a pleasant maze of hedges.",
    "gmaz24": "you are wandering in a pleasant maze of hedges.",
    "gmaz25": "maze of hedges",
    "gmaz26": "maze of hedges",
    "gmaz27": "maze of hedges",
    "gmaz28": "you are wandering in a pleasant maze of hedges.",
    "gmaz29": "you are wandering in a pleasant maze of hedges.",
    "gmaz3": "maze of hedges",
    "gmaz30": "maze of hedges",
    "gmaz31": "maze of hedges",
    "gmaz32": "you are wandering in a pleasant maze of hedges.",
    "gmaz33": "you are wandering in a pleasant maze of hedges.",
    "gmaz34": "maze of hedges",
    "gmaz35": "maze of hedges",
    "gmaz36": "maze of hedges",
    "gmaz37": "you are wandering in a pleasant maze of hedges.",
    "gmaz38": "you are wandering in a pleasant maze of hedges.",
    "gmaz39": "you are wandering in a pleasant maze of hedges.",
    "gmaz4": "maze of hedges",
    "gmaz40": "maze of hedges",
    "gmaz41": "you are wandering in a pleasant maze of hedges.",
    "gmaz42": "maze of hedges",
    "gmaz43": "maze of hedges",
    "gmaz44": "maze of hedges",
    "gmaz45": "maze of hedges",
    "gmaz46": "maze of hedges",
    "gmaz47": "maze of hedges",
    "gmaz48": "you are wandering in a pleasant maze of hedges.",
    "gmaz49": "maze of hedges",
    "gmaz5": "maze of hedges",
    "gmaz50": "you are wandering in a pleasant maze of hedges.",
    "gmaz51": "you are wandering in a pleasant maze of hedges.",
    "gmaz52": "maze of hedges",
    "gmaz53": "maze of hedges",
    "gmaz54": "you are wandering in a pleasant maze of hedges.",
    "gmaz55": "maze of hedges",
    "gmaz56": "maze of hedges",
    "gmaz57": "you are wandering in a pleasant maze of hedges.",
    "gmaz58": "maze of hedges",
    "gmaz59": "maze of hedges",
    "gmaz6": "maze of hedges",
    "gmaz60": "maze of hedges",
    "gmaz61": "you are wandering in a pleasant maze of hedges.",
    "gmaz62": "maze of hedges",
    "gmaz63": "you are wandering in a pleasant maze of hedges.",
    "gmaz64": "maze of hedges",
    "gmaz65": "you are standing in the centre of a pleasant maze of hedges.",
    "gmaz66": "you are wandering in a pleasant maze of hedges.",
    "gmaz67": "you are wandering in a pleasant maze of hedges.",
    "gmaz68": "you are wandering in a pleasant maze of hedges.",
    "gmaz7": "maze of hedges",
    "gmaz8": "you are wandering in a pleasant maze of hedges.",
    "gmaz9": "maze of hedges",
    "gmazent": "entrance to maze",
    "gmustemp": "music temple",
    "gndeer": "deerpark",
    "gnook": "sheltered nook",
    "gnymph": "nympheum",
    "goak": "fallen oak tree",
    "gopanth": "outside pantheon",
    "gorange": "orangery",
    "gorchard": "orchard in formal garden",
    "gpanth": "pantheon",
    "gpen1": "peninsula",
    "gpen2": "peninsula",
    "gpergo": "pergola",
    "gpond": "pond in luscious wood",
    "grhodo": "rhododendron tunnel",
    "groad1": "dally lane",
    "groad2": "dally lane",
    "groad3": "dally lane",
    "gsdeer": "deerpark",
    "gshelwk": "sheltered walk",
    "gspinrm": "spinning room",
    "gsteps": "steps of music temple",
    "gstream1": "stream in wood",
    "gstream2": "stream in luscious wood",
    "gstream3": "stream in luscious wood",
    "gstream4": "stream in luscious wood",
    "gsummer": "summerhouse",
    "gterr": "ruined terrace",
    "gwall": "walled garden",
    "gwdeer": "deerpark",
    "gwhite": "white garden",
    "gwood1": "luscious wood",
    "gwood2": "luscious wood",
    "gyard": "yard",
    "hcavn": "huge cavern",
    "heaven": "heaven",
    "home": "Wizzes' room",
    "hospic": "pilgrims' hospice",
    "ingfc": "inside grandfather clock",
    "ingres": "ingresso",
    "istep1": "cellar steps",
    "istep2": "inn steps",
    "istep3": "inn steps",
    "istep4": "inn steps",
    "itoilets": "toilets",
    "kitchn": "kitchen in inn",
    "laundry": "laundry",
    "lbar": "lounge bar",
    "lioanc": "library of ancestors",
    "loggia": "loggia",
    "maltar": "sacred room",
    "mantech": "ante chamber",
    "mattic": "attic",
    "mbathrm": "bathroom",
    "mbbath": "bird bath in pine forest",
    "mbdrm01": "large bedroom",
    "mbdrm02": "main bedroom",
    "mbdrm03": "small bedroom",
    "mbeach": "rocky beach",
    "mbeach2": "bottom of waterfall",
    "mbeach3": "stony beach",
    "mbeach4": "stony beach",
    "mbed1": 'master bedroom in "il castellare"',
    "mbed2": 'master bedroom in "il castellare"',
    "mbef1": "before idol",
    "mbefcit": "before citadel",
    "mbefgte": "before gate",
    "mbldg": "bottom of ledge",
    "mbluerm": "blue room",
    "mbrost": "beneath ring of stones",
    "mbstand": "bandstand",
    "mbunker": "coal bunker",
    "mbwfall": "behind waterfall",
    "mcannrm": "cannon room",
    "mcapt": "captain's cabin",
    "mcave": "cave",
    "mcavein": "caved-in grave",
    "mcellar": "cellar",
    "mchambr": "ancient chamber",
    "mcinder": "cindered room",
    "mclffst": "dense forest",
    "mclifff": "cliff",
    "mcove": "cove",
    "mcrookp": "crooked passage",
    "mcrow": "crow's nest",
    "mcrrm": "crack room",
    "mcrypt": "ancient crypt",
    "mcupd1": "airing cupboard",
    "mcupd2": "fitted cupboard",
    "mcuptop": "top of cupboard",
    "mcurve": "curved passage",
    "mcuttin": "railway cutting",
    "mdcliff": "dangerous cliff",
    "mdeathp": "deathly passage",
    "mdeck": "deck",
    "mdiagps": "diagonal passage",
    "mdiamnd": "diamond room",
    "mdining": "dining area",
    "mdoomrm": "doom room",
    "mdorm": "dormitory",
    "mdownps": "narrow passage",
    "mdpass1": "dangerous passage",
    "mdpass2": "dangerous passage",
    "mdpass3": "dangerous passage",
    "mdpass4": "dangerous passage",
    "mdpass5": "dangerous passage",
    "mdpass6": "dangerous passage",
    "mdsteps": "steps to cellar",
    "mdtest1": "steps down",
    "mdtest2": "niche room",
    "mdtest3": "druid room",
    "mdtreas": "druidical treasure chamber",
    "mdwbog": "dwarf lavatory",
    "mdwcant": "canteen",
    "mdwfood": "food store",
    "mdwhall": "dwarfen hall",
    "mdwktch": "dwarf kitchen",
    "mdwpit": "refuse pit",
    "mdwpst1": "dwarfen pasture",
    "mdwpst2": "dwarfen pasture",
    "mdwrm1": "dwarf room",
    "mdwrm2": "dwarf room",
    "mdwrm3": "dwarf room",
    "mdwrm4": "dwarf room",
    "mdwroom": "dwarf room",
    "mdwstep": "dwarf steps",
    "mdwstre": "dwarf store",
    "medwrlm": "entrance to dwarf realm",
    "meetrm": "meeting room",
    "mefrst1": "forest at base of cliff",
    "memine": "entrance to mine",
    "mentrnc": "entrance to citadel",
    "mepstre": "east pasture",
    "mestlpl": "east side of still pool",
    "metomb": "east tomb",
    "mewstep": "east-west steps",
    "meyedol": "nose and eye of idol",
    "mface1": "face",
    "mface2": "face",
    "mface3": "face",
    "mface4": "face",
    "mfallin": "falling off cliff",
    "mfallint": "falling off cliff",
    "mfirept": "fiery pit",
    "mforist": "dense forest",
    "mfortun": "forbidding tunnel",
    "mfossrm": "fossil room",
    "mfowrm": "fountain room",
    "mfring": "fairy ring",
    "mfslop1": "forest on steep slope",
    "mfslop2": "forest on steep slope",
    "mfslop3": "forest on steep slope",
    "mgalley": "galley",
    "mgaptrm": "golden appletree in pine forest",
    "mgarden": "flower garden",
    "mglade": "magical glade",
    "mgob1": "goblin lair",
    "mgob2": "goblin lair",
    "mgob3": "goblin lair",
    "mgob4": "goblin lair",
    "mgob5": "goblin lair",
    "mgorse": "gorse",
    "mgrotto": "grotto",
    "mguadrm": "guard room",
    "mguard1": "dwarf guard room",
    "mguard2": "dwarf guard room",
    "mguard3": "dwarf guard room",
    "mguard4": "dwarf guard room",
    "mhall": "hall",
    "mhchamb": "hallowed chamber",
    "mhdland": "headland",
    "mhold": "hold",
    "mhollow": "hollowed-out passage",
    "mhotpas": "hot passage",
    "mhut": "woodsman's hut",
    "midriv1": "midriver",
    "mifrst1": "arcane forest",
    "mifrst2": "arcane forest",
    "mifrst3": "oak forest",
    "mifrst4": "sloping forest",
    "mifrst5": "thicket",
    "mifrst6": "sloping forest",
    "minlet": "concealed inlet",
    "minmth": "inside mouth of idol",
    "minsett": "inside badger's sett",
    "misanct": "inner sanctum",
    "mjetty": "jetty",
    "mkdorm": "children's dormitory",
    "mkingrm": "throne room",
    "mkingst": "king's study",
    "mkitche": "kitchen",
    "mkqdorm": "royal bedroom",
    "mktreas": "king's treasure chamber",
    "mladdrm": "ladder shaft",
    "mlandin": "upstairs landing",
    "mledge1": "ledge",
    "mledge2": "ledge",
    "mledge3": "ledge",
    "mleprm": "leprechaun room",
    "mlevel": "level room",
    "mlgrm": "large room",
    "mlionrm": "pine forest",
    "mlongps": "long passage",
    "mlounge": "lounge",
    "mlowps1": "low passage",
    "mlowps2": "low passage",
    "mlowps3": "low passage",
    "mlowps4": "low passage",
    "mlowps5": "low passage",
    "mlowps6": "low passage",
    "mlowps7": "low passage",
    "mlowps8": "low passage",
    "mlowps9": "low passage",
    "mlsp1": "long sloping passage",
    "mlsp2": "long sloping passage",
    "mlsp3": "long sloping passage",
    "mmain1": "main passage",
    "mmain2": "main passage",
    "mmain3": "main passage",
    "mmain4": "main passage",
    "mmain5": "main passage",
    "mmain6": "main passage",
    "mmain7": "main passage",
    "mmaze1": "misty graveyard",
    "mmaze10": "you are lost in a misty graveyard.",
    "mmaze2": "misty graveyard",
    "mmaze25": "you are standing in front of a large tombstone.",
    "mmaze3": "you are lost in a misty graveyard.",
    "mmaze4": "misty graveyard",
    "mmaze5": "misty graveyard",
    "mmaze6": "misty graveyard",
    "mmaze7": "misty graveyard",
    "mmaze8": "misty graveyard",
    "mmaze9": "misty graveyard",
    "mmcrypt": "crypt beneath church",
    "mmfrst": "forest near mountains",
    "mminor1": "minor passage",
    "mminor2": "minor passage",
    "mminor3": "minor passage",
    "mminor5": "minor passage",
    "mminor6": "minor passage",
    "mminor7": "minor passage",
    "mminor8": "minor passage",
    "mminrm": "ministerial room",
    "mmosolm": "mausoleum",
    "mmthidl": "outside mouth of idol",
    "mmudrm": "mud room",
    "mnatcav": "natural cavern",
    "mnbank": "north bank of underground river",
    "mndale": "north dale",
    "mnest": "eagle's nest",
    "mnetomb": "northeast tomb",
    "mnfrst1": "dense forest",
    "mnfrst2": "dense forest",
    "mnfrst3": "dense forest",
    "mnfrst4": "dense forest",
    "mnfrst5": "dense forest",
    "mnfrst6": "dense forest",
    "mnfrst7": "dense forest",
    "mnhill1": "foothills",
    "mnhill2": "foothills",
    "mnstep1": "narrow steps",
    "mnstep2": "narrow steps",
    "mnstep3": "narrow steps",
    "mntomb": "north tomb",
    "modorm": "officers' dormitory",
    "moglair": "ogre's lair",
    "mogrnds": "overgrown grounds of mausoleum",
    "mohut": "in front of hut",
    "monalt": "high altar",
    "monapse": "apse in abbatial church",
    "monbch1": "before north chapel",
    "monbch2": "before south chapel",
    "monch": "abbatial church",
    "monch1": "north chapel in abbatial church",
    "monch2": "south chapel in abbatial church",
    "monent": "entrance to monastery",
    "monfon": "font in abbatial church",
    "monkit": "monastery kitchen",
    "monnav": "nave in abbatial church",
    "monport": "entrance to abbatial church",
    "monstab": "stables",
    "monstyd": "stable yard",
    "montrn": "transept in abbatial church",
    "mosanct": "outer sanctum",
    "mostart": "road opposite cottage",
    "mpaddck": "paddock",
    "mpanora": "panoramic view",
    "mpantry": "pantry",
    "mpass10": "passage",
    "mpassg1": "passage",
    "mpassg2": "passage",
    "mpassg3": "passage",
    "mpassg4": "passage",
    "mpassg5": "passage",
    "mpassg6": "passage",
    "mpassg7": "passage",
    "mpassg8": "passage",
    "mpassg9": "passage",
    "mpatch": "vegetable garden",
    "mpath": "path",
    "mpdorm": "married quarters",
    "mperil1": "Perilous passage",
    "mperil2": "Perilous passage",
    "mperil3": "Perilous passage",
    "mperil4": "Perilous passage",
    "mperil5": "Perilous passage",
    "mpines1": "pine forest",
    "mpines2": "pine forest",
    "mpines3": "pine forest",
    "mpines4": "pine forest",
    "mpines5": "pine forest",
    "mpines6": "pine forest",
    "mpines7": "pine forest",
    "mplatfm": "platform",
    "mpond1": "pond in swamp",
    "mpoop": "poop deck",
    "mproom": "powder room",
    "mrail1": "railway track",
    "mrail2": "railway track",
    "mrail3": "railway track",
    "mrail4": "railway track",
    "mrapids": "rapids",
    "mrattun": "rat tunnel",
    "mrevps": "reverberating passage",
    "mrevrm": "reverberating room",
    "mriver1": "river",
    "mriver2": "river",
    "mriver3": "underground river",
    "mroad2": "narrow road",
    "mrockps": "rock passage",
    "mroot": "root room",
    "mrost": "ring of stones",
    "mrottrm": "rotting room",
    "mrsteps": "roughly hewn steps",
    "mrtun1": "root tunnel",
    "mrtun2": "northern part of root tunnel",
    "mruin": "ruin",
    "msaltar": "small altar room",
    "mschamb": "small chamber",
    "mscrubs": "scrub slope",
    "msdale": "south dale",
    "msea0": "sea",
    "msea1": "sea",
    "msea10": "small bay",
    "msea11": "sea",
    "msea12": "sea",
    "msea13": "sea",
    "msea14": "sea",
    "msea15": "sea",
    "msea16": "sea",
    "msea2": "sea",
    "msea3": "sea",
    "msea4": "sea",
    "msea5": "sea",
    "msea6": "sea",
    "msea7": "sea",
    "msea8a": "sea",
    "msea8b": "sea",
    "msea9": "sea",
    "msectn": "section of main passage",
    "msetomb": "southeast tomb",
    "msett": "entrance to badger's sett",
    "msfrst1": "dense forest",
    "msfrst2": "dense forest",
    "mshaft1": "vertical shaft",
    "mshaft2": "vertical shaft",
    "mshaft3": "vertical shaft",
    "mshaft4": "vertical shaft",
    "mshed": "shed",
    "mshill1": "foothills",
    "mshill2": "foothills",
    "mshrine": "shrine",
    "msidpsg": "side passage",
    "mslidin": "sliding down chute",
    "mslidint": "sliding down chute",
    "mslope1": "steep slope",
    "mslope2": "steep slope",
    "mslope3": "steep slope",
    "mslope4": "steep slope",
    "msloptn": "sloping tunnel",
    "msmuggl": "smugglers' cave",
    "msorcrm": "sorcerer's room",
    "mspanel": "sliding panel room",
    "mspiral": "spiral staircase",
    "msplair": "spider's lair",
    "mspring": "spring",
    "mspstre": "south pasture",
    "msqrm": "squirrel part of forest",
    "msrock1": "slippery rocks",
    "msrock2": "slippery rocks",
    "msrock3": "slippery rocks",
    "mssteps": "secret steps",
    "mstairs": "halfway up the stairs",
    "mstart": "narrow road between lands",
    "mstomb": "south tomb",
    "mstpoop": "steps",
    "mstslop": "stony slope",
    "mstudy": "study",
    "mstun1": "small tunnel",
    "mstun10": "small tunnel",
    "mstun2": "small tunnel",
    "mstun3": "small tunnel",
    "mstun4": "small tunnel",
    "mstun5": "small tunnel",
    "mstun6": "small tunnel",
    "mstun7": "small tunnel",
    "mstun8": "small tunnel",
    "mstun9": "small tunnel",
    "mswamp1": "treacherous swamp",
    "mswamp2": "treacherous swamp",
    "mswamp3": "treacherous swamp",
    "mswamp4": "treacherous swamp",
    "mswamp5": "you are waylaid in a treacherous swamp",
    "mswamp6": "treacherous swamp",
    "mswamp7": "you are standing in a drier part of the swamp.",
    "mswamp8": "treacherous swamp",
    "mswamp9": "treacherous swamp",
    "mswampa": "treacherous swamp",
    "mswampb": "you are waylaid in a treacherous swamp",
    "mswampc": "treacherous swamp",
    "mswampd": "treacherous swamp",
    "mswampe": "treacherous swamp",
    "mswtomb": "southwest tomb",
    "mtemple": "temple",
    "mtightp": "tight passage",
    "mtombrm": "tomb room",
    "mtopcit": "top of citadel",
    "mtrack1": "beaten track near cliff",
    "mtrack2": "beaten track",
    "mtreasc": "treasure chamber",
    "mtun1": "tunnel in monastery",
    "mtun2": "tunnel in monastery",
    "mtunnel": "earth tunnel",
    "mufrst1": "underground forest",
    "mufrst2": "underground forest",
    "mufrst3": "underground forest",
    "mufrst5": "underground forest",
    "muhut": "underground room",
    "muland1": "staircase landing",
    "muland2": "bottom of worn steps",
    "muland3": "bottom of stairs",
    "mvalvrm": "valve on staircase",
    "mvert": "vertical staircase",
    "mvrocks": "vicious rocks",
    "mwabe": "sundial in pine forest",
    "mwdale": "west dale",
    "mwfall": "waterfall",
    "mwfrst1": "dense forest",
    "mwhroom": "pine forest",
    "mwoe1": "north part of isle of woe",
    "mwoe2": "south part of isle of woe",
    "mwolfrm": "wolf room",
    "mwpnstr": "weapon store",
    "mwpstre": "west pasture",
    "mwrdbe": "fitted wardrobe",
    "mwstep1": "worn steps",
    "mwstep2": "worn steps",
    "mwstep3": "worn steps",
    "mwstlpl": "west side of still pool",
    "mwtomb": "west tomb",
    "mzroom": "zombie room",
    "nattic": "north part of attic",
    "neclo": "northeastern corner of cloisters",
    "nness": "nothingness",
    "npass1": "narrow passage",
    "npass2": "narrow passage",
    "npass3": "narrow passage",
    "nwclo": "northwestern corner of cloisters",
    "ocbed2": 'outside bedroom in "il castellare"',
    "ogardn": "overgrown garden",
    "olive1": "olive grove",
    "olive2": "olive grove",
    "olive3": "olive grove",
    "olive4": "olive grove",
    "olive5": "olive grove",
    "olive6": "olive grove",
    "olive7": "olive grove",
    "opave": "paved yard",
    "partrm": "party room",
    "pcave1": "prehistoric cave",
    "pcave2": "Prehistoric cave",
    "pigsty": "pigsty",
    "pulpit": "pulpit",
    "pumphs": "pumphouse",
    "quitbox": "quit box",
    "refect": "refectory",
    "relirm": "relics room",
    "rokpit": "rocky pit",
    "room10": "bridal suite",
    "room11": "room 11",
    "room12": "room 12",
    "room13": "room 13",
    "room14": "room 14",
    "room15": "room 15",
    "room16": "room 16",
    "room20": "room 20",
    "room21": "room 21",
    "room22": "room 22",
    "sattic": "south part of attic",
    "scrip1": "room in scriptorium",
    "scrip10": "room in scriptorium",
    "scrip11": "room in scriptorium",
    "scrip12": "room in scriptorium",
    "scrip13": "room in scriptorium",
    "scrip14": "room in scriptorium",
    "scrip15": "room in scriptorium",
    "scrip16": "room in scriptorium",
    "scrip17": "room in scriptorium",
    "scrip18": "room in scriptorium",
    "scrip19": "room in scriptorium",
    "scrip2": "room in scriptorium",
    "scrip20": "room in scriptorium",
    "scrip21": "room in scriptorium",
    "scrip22": "room in scriptorium",
    "scrip23": "room in scriptorium",
    "scrip24": "room in scriptorium",
    "scrip25": "room in scriptorium",
    "scrip26": "room in scriptorium",
    "scrip27": "room in scriptorium",
    "scrip28": "room in scriptorium",
    "scrip29": "room in scriptorium",
    "scrip3": "room in scriptorium",
    "scrip30": "room in scriptorium",
    "scrip31": "room in scriptorium",
    "scrip32": "room in scriptorium",
    "scrip33": "room in scriptorium",
    "scrip34": "room in scriptorium",
    "scrip35": "room in scriptorium",
    "scrip36": "room in scriptorium",
    "scrip37": "room in scriptorium",
    "scrip38": "room in scriptorium",
    "scrip39": "room in scriptorium",
    "scrip4": "room in scriptorium",
    "scrip40": "room in scriptorium",
    "scrip41": "room in scriptorium",
    "scrip42": "room in scriptorium",
    "scrip43": "room in scriptorium",
    "scrip44": "room in scriptorium",
    "scrip45": "room in scriptorium",
    "scrip46": "room in scriptorium",
    "scrip47": "room in scriptorium",
    "scrip48": "room in scriptorium",
    "scrip49": "room in scriptorium",
    "scrip5": "room in scriptorium",
    "scrip50": "room in scriptorium",
    "scrip51": "room in scriptorium",
    "scrip52": "room in scriptorium",
    "scrip53": "room in scriptorium",
    "scrip6": "room in scriptorium",
    "scrip7": "room in scriptorium",
    "scrip8": "room in scriptorium",
    "scrip9": "room in scriptorium",
    "seclo": "southeastern corner of cloisters",
    "sky": "high in the sky",
    "snug": "snug",
    "spirst": "spirit store",
    "stalrm": "stalagmite room",
    "storrm": "storage room",
    "strng": "strongroom",
    "swclo": "southwestern corner of cloisters",
    "swpool": "swimming pool",
    "tabhole": "above hole",
    "tacol1": "acolyte's room",
    "tacol2": "acolyte's room",
    "tacol3": "acolyte's room",
    "tacol4": "acolyte's room",
    "tafrst1": "mixed forest",
    "tafrst2": "mixed forest",
    "tafrst3": "mixed forest",
    "tafrst4": "mixed forest",
    "talpctg": "inside alpine cottage",
    "taltarm": "buddhist altar",
    "tamasrm": "assistant master's room",
    "tape1": "ape forest",
    "tape2": "ape forest",
    "tape3": "ape forest",
    "tape4": "ape forest",
    "tape5": "ape forest",
    "tbambrg": "bamboo bridge",
    "tbedrm": "bedroom in alpine cottage",
    "tbefgg": "before great gate",
    "tbefmt": "before minor temple",
    "tbefvw": "before venerated wall",
    "tbefwg": "before west gate",
    "tbliz1": "you are stumbling around in a blizzard",
    "tbliz10": "you are stumbling around in a blizzard",
    "tbliz11": "you are stumbling around in a blizzard",
    "tbliz12": "you are stumbling around in a blizzard",
    "tbliz2": "you are stumbling around in a blizzard",
    "tbliz3": "you are stumbling around in a blizzard",
    "tbliz4": "you are stumbling around in a blizzard",
    "tbliz5": "you are stumbling around in a blizzard",
    "tbliz6": "you are stumbling around in a blizzard",
    "tbliz7": "you are stumbling around in a blizzard",
    "tbliz8": "you are stumbling around in a blizzard",
    "tbliz9": "you are stumbling around in a blizzard",
    "tbongdn": "bonsai garden",
    "tcedar1": "cedar forest",
    "tcedar2": "cedar forest",
    "tcedar3": "cedar forest",
    "tcedar4": "cedar forest",
    "tcedar5": "cedar forest",
    "tcedar6": "cedar forest",
    "tcedar7": "cedar forest",
    "tcedar8": "cedar forest",
    "tcedar9": "cedar forest",
    "tchrgdn": "chrysanthemum garden",
    "tclerng": "clearing in mixed forest",
    "tcopse1": "copse",
    "tcopse2": "copse",
    "tcrevce": "edge of crevice",
    "tcupbrd": "cupboard in alpine cottage",
    "tcwalk": "central walk",
    "tdihall": "dining hall",
    "tdinrm": "dining room in alpine cottage",
    "tecloie": "eastern entrance to cloisters",
    "tewind": "Room of the east wind",
    "tfield1": "open field",
    "tfield2": "open field",
    "tfloor1": "first floor of pagoda",
    "tfloor2": "Second floor of pagoda",
    "tfloor3": "third floor of pagoda",
    "tfloor4": "top floor of pagoda",
    "tfoodst": "food storage room",
    "tfprep": "food preparation area",
    "tfunrl": "funeral room",
    "tgardn": "tangled garden",
    "tgbudrm": "before great buddha",
    "tgpool": "glassy pool",
    "tgrass1": "grassy area",
    "tgrass2": "grassy area",
    "tgrass3": "grassy area",
    "tgrass4": "grassy area",
    "tgrdorm": "greater dormitory",
    "thinlg": "thin ledge",
    "thrbgdn": "herb garden",
    "tjasgdn": "jasmine garden",
    "tlbudrm": "before large buddha",
    "tlfrst1": "low forest",
    "tlfrst2": "low forest",
    "tlfrst3": "low forest",
    "tlfrst4": "low forest",
    "tlfrst5": "low forest",
    "tlfrst6": "low forest",
    "tlfrst7": "low forest",
    "tlfrst8": "low forest",
    "tlibrary": "library",
    "tlotgdn": "lotus garden",
    "tlrchrm": "larch garden",
    "tlrdorm": "lesser dormitory",
    "tmajort": "major temple",
    "tmasrm": "master's room",
    "tmedit1": "meditation room",
    "tmedit2": "meditation room",
    "tminort": "minor temple",
    "tmossp1": "mossy path",
    "tmossp2": "mossy path",
    "tmossp3": "mossy path",
    "tncourt": "north part of courtyard",
    "tnepstre": "northeast pasture",
    "tnwalk": "northern walk",
    "tnwind": "Room of the north wind",
    "tordntn": "ordination room",
    "towrm1": "tower stairs",
    "towrm2": "landing in tower",
    "towrm3": "landing in tower",
    "towrm4": "nursery in tower",
    "towrm5": "nanny's room",
    "tpfunrl": "priests' funeral room",
    "trapd": "chute",
    "trevpth": "revered path",
    "trhogdn": "rhododendron garden",
    "trockry": "rockery",
    "trocky1": "rocky path",
    "trocky2": "rocky path",
    "trocky3": "rocky path in forest",
    "trocky4": "rocky path in forest",
    "trocky5": "rocky path along ridge",
    "trocky6": "rocky path along ridge",
    "trocky7": "rocky path in clouds",
    "trocky8": "snow-covered rocky path",
    "trocky9": "snow-covered rocky path",
    "tsbudrm": "before seated buddha",
    "tscourt": "south part of courtyard",
    "tscram1": "rocky scramble",
    "tscram2": "rocky scramble",
    "tscram3": "rocky scramble",
    "tscram4": "rocky scramble",
    "tscram5": "rocky scramble",
    "tscram6": "rocky scramble near summit",
    "tscrnrm": "screened-off room",
    "tshelf1": "ice shelf",
    "tshelf2": "ice shelf",
    "tshelf3": "ice shelf",
    "tshelp1": "sheltered path",
    "tshelp2": "sheltered path",
    "tshelp3": "sheltered path",
    "tshelp4": "sheltered path",
    "tshelp5": "sheltered path",
    "tshrub1": "shrubbery",
    "tshrub2": "shrubbery",
    "tsnow1": "snowy mountainside",
    "tsnow2": "snowy mountainside",
    "tsnow3": "snowy mountainside",
    "tsnow4": "snowy mountainside",
    "tsnow5": "snowdrift",
    "tsnow6": "snowy mountainside",
    "tsnow7": "snowy mountainside before cottage",
    "tspinny": "spinney",
    "tstatrm": "statuary in mixed forest",
    "tstempl": "small temple",
    "tswalk": "southern walk",
    "tswind": "Room of the south wind",
    "ttentrn": "entrance to temple",
    "tthrhld": "threshhold of pagoda",
    "ttonm": "top of north mountain",
    "ttoolrm": "tool room",
    "ttpath1": "tranquil path",
    "ttpath2": "tranquil path",
    "ttpath3": "tranquil path",
    "ttpool": "tinkling pool",
    "ttranq1": "tranquil walk",
    "ttranq2": "tranquil walk",
    "ttranq3": "tranquil walk",
    "ttranq4": "tranquil walk",
    "ttyph": "Room of typhoons",
    "tunused": "unused room",
    "tvineyd": "vineyard",
    "twardrb": "wardrobe in alpine cottage",
    "twcloie": "western entrance to cloisters",
    "tweddin": "wedding room",
    "twedgdn": "weed garden",
    "twellrm": "well room",
    "twepnrm": "weapon room",
    "twpath": "wide path",
    "twwind": "Room of the west wind",
    "ucave": "underground cave",
    "uisle": "underground island",
    "ulake1": "underground lake",
    "ulake2": "underground lake",
    "ulake3": "underground lake",
    "ulake4": "underground lake",
    "ulake5": "underground lake",
    "ulake6": "underground lake",
    "ulamprm": "inside the lamp",
    "uphall": "upstairs corridor",
    "uppas1": "upstairs passage",
    "uppas2": "upstairs passage",
    "uppas3": "upstairs passage",
    "uppas4": "upstairs passage",
    "uppas5": "upstairs passage",
    "uscrip": "ground floor of scriptorium",
    "ustrm1": "underground stream",
    "ustrm2": "underground stream",
    "ustrm3": "underground stream",
    "ustrm4": "underground confluence",
    "ustrm5": "underground river",
    "ustrm6": "Underground stream",
    "ustrm7": "underground river",
    "ustrm8": "underground river",
    "ustrm9": "underground river",
    "ustrma": "underground stream",
    "ustrmb": "underground stream",
    "ustrmc": "underground stream",
    "ustrmd": "small underground stream",
    "ustrme": "underground stream",
    "uwell1": "under well",
    "uwell2": "under well",
    "uwell3": "under well",
    "uwell4": "inside well",
    "uwell5": "inside well",
    "uwell6": "bottom of well",
    "uwell7": "near top of well",
    "vbank1": "bank of river",
    "vbank2": "bank of river",
    "vbank3": "bank of river",
    "vbank4": "bank of river",
    "vbank5": "bank of river",
    "vbelfry": "inside belfry",
    "vbriar": "briar patch",
    "vbridge": "bridge over river",
    "vefrst1": "dense forest",
    "vepstre": "east lush pasture",
    "vewd1": "evil wood",
    "vewd10": "evil wood",
    "vewd2": "evil wood",
    "vewd3": "evil wood",
    "vewd4": "evil wood",
    "vewd5": "evil wood",
    "vewd6": "evil wood",
    "vewd7": "evil wood",
    "vewd8": "evil wood",
    "vewd9": "evil wood",
    "vgal": "viewing gallery",
    "vgazebo": "inside gazebo",
    "vheath1": "rough heath",
    "vheath2": "rough heath",
    "vheath3": "rough heath",
    "vheath4": "rough heath",
    "visland": "small island",
    "vmeadow": "riverside meadow",
    "vmmtn1": "middle mountain",
    "vmmtn10": "top of middle mountain",
    "vmmtn2": "middle mountain",
    "vmmtn3": "middle mountain",
    "vmmtn4": "middle mountain",
    "vmmtn5": "middle mountain",
    "vmmtn6": "misty part of middle mountain",
    "vmmtn7": "misty part of middle mountain",
    "vmmtn8": "misty part of middle mountain",
    "vmmtn9": "misty part of middle mountain",
    "vnfrst1": "dense forest",
    "vnfrst2": "dense forest",
    "vnfrst3": "dense forest",
    "vnhill1": "foothills",
    "vnhill2": "foothills",
    "vnhill3": "foothills",
    "vnmtn1": "forested part of north mountain",
    "vnmtn2": "north mountain",
    "vnmtn3": "north mountain",
    "vnmtn4": "north mountain",
    "vnmtn5": "north mountain",
    "vnmtn6": "north mountain",
    "vnmtn7": "north mountain",
    "vnmtn8": "north mountain",
    "vnpstre": "north lush pasture",
    "vorchrd": "ancient orchard",
    "vpines1": "pine forest",
    "vriver1": "ford in river",
    "vriver2": "fast-flowing river",
    "vriver3": "fast-flowing river",
    "vriver4": "fast-flowing river",
    "vroad1": "badly-paved road",
    "vroad2": "badly-paved road",
    "vroad3": "badly-paved road",
    "vroad4": "badly-paved road",
    "vrough": "rough pasture",
    "vsfrst1": "dense forest",
    "vsfrst2": "dense forest",
    "vshill1": "foothills",
    "vshill2": "foothills",
    "vsmtn1": "south mountain",
    "vsmtn2": "south mountain",
    "vsmtn3": "forested part of south mountain",
    "vsmtn4": "misty part of south mountain",
    "vsmtn5": "misty part of south mountain",
    "vsmtn6": "misty part of south mountain",
    "vsmtn7": "south mountain",
    "vsmtn8": "misty part of south mountain",
    "vsmtn9": "top of south mountain",
    "vspstre": "south lush pasture",
    "vstable": "stable",
    "vstart": "ford across river",
    "vswamp1": "fuming swamp",
    "vuswamp": "bottom of swamp",
    "vvalley": "valley between mountains",
    "vwellrm": "well near inn",
    "vwfrst1": "dense forest",
    "vwpstre": "west lush pasture",
    "vyard1": "side yard of inn",
    "vyard2": "back yard of inn",
    "walc": "west alcove",
    "walk1": "avenue",
    "walk2": "avenue",
    "wante": "west antechamber",
    "wattic": "west part of attic",
    "wayinn": "entrance hall",
    "winest": "wine store",
    "wkshop": "workshop",
    "wthstp": "weathered steps",
    "xmasbx": "christmas box",
}

# Rooms which are unreachable to mortals during a regular game.
WIZ_ROOM_IDS = (
    "confrm",
    "Limbo",
    "((wwork))",
    "((store))",
    "home",
    "ahome",
)

ROOM_IDS = sorted(ROOM_NAME_BY_ID)
ROOM_NAMES = sorted({room_name.lower() for room_name in ROOM_NAME_BY_ID.values()})

MORTAL_ROOM_IDS = [room_id for room_id in ROOM_IDS if room_id not in WIZ_ROOM_IDS]
MORTAL_ROOM_NAMES = [ROOM_NAME_BY_ID[room_id].lower() for room_id in MORTAL_ROOM_IDS]
